name: Pylint

on:
  push:
    branches: [ main, live ]
  pull_request:
    branches: [ main, live ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies (user auth)
      working-directory: user-auth/graphtutorial
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analyzing the code with pylint (user auth)
      working-directory: user-auth/graphtutorial
      run: |
        pylint $(git ls-files '*.py')
    - name: Install dependencies (app auth)
      working-directory: app-auth/graphapponlytutorial
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
    - name: Analyzing the code with pylint (app auth)
      working-directory: app-auth/graphapponlytutorial
      run: |
        pylint $(git ls-files '*.py')
